program_name: "Program Name"
program_description: "Brief description of the program"

# Target configuration
targets:
  staging: "https://staging.example.com"
  production: "https://example.com"
  api_docs: "https://docs.example.com"

# Endpoints to check
endpoints:
  - "/api/v1/"
  - "/api/v2/"
  - "/auth/"
  - "/login"
  - "/register"
  - "/reset-password"
  - "/profile"
  - "/settings"
  - "/admin/"
  - "/upload/"
  - "/download/"
  - "/export/"
  - "/import/"

# Authentication endpoints
auth_endpoints:
  - "/login"
  - "/register"
  - "/reset-password"
  - "/oauth/authorize"
  - "/oauth/token"

# Nuclei templates to run
nuclei_templates:
  - "cves/"
  - "exposures/"
  - "misconfiguration/"
  - "vulnerabilities/"

# Custom checks specific to the program
custom_checks:
  - name: "Check Payment Processing"
    type: "api"
    endpoint: "/api/payment"
    method: "POST"
    details:
      test_cards: true
      webhook_testing: true

  - name: "Check File Upload"
    type: "file"
    endpoint: "/upload"
    method: "POST"
    details:
      max_size: "10MB"
      allowed_types: ["jpg", "png", "pdf"]

# Program-specific settings
settings:
  max_concurrent_requests: 5
  request_timeout: 5
  retry_attempts: 3
  follow_redirects: true

# Report configuration
reporting:
  format: "json"
  include_headers: true
  include_response_body: false
  save_screenshots: true 